import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const root=process.cwd(),client=path.join(root,'client');
const ts=require(require.resolve('typescript',{paths:[client]}));
const config=ts.readConfigFile(path.join(client,'tsconfig.app.json'),ts.sys.readFile);
const parsed=ts.parseJsonConfigFileContent(config.config,ts.sys,client,{},path.join(client,'tsconfig.app.json'));
const siteFiles=parsed.fileNames.filter(f=>f.includes('/src/site/')||f.endsWith('/vite-env.d.ts'));
const program=ts.createProgram(siteFiles,parsed.options);
const diagnostics=ts.getPreEmitDiagnostics(program).map(d=>({file:d.file?path.relative(root,d.file.fileName):'',code:d.code,message:ts.flattenDiagnosticMessageText(d.messageText,' ')}));
const site=diagnostics.filter(d=>d.file.includes('/src/site/')),dependencies=diagnostics.filter(d=>!d.file.includes('/src/site/'));
fs.writeFileSync('design-demos/portfolio-redesign/verification-site-types.json',JSON.stringify({siteFiles:siteFiles.length,siteErrors:site,dependencyDiagnostics:dependencies},null,2));
console.log(JSON.stringify({siteFiles:siteFiles.length,siteErrors:site,dependencyDiagnostics:dependencies}));if(site.length)process.exitCode=1;
