import { Link } from 'react-router-dom';
import { usePageMeta } from '../../shared/hooks/usePageMeta';
import { usePageTracker } from '../../shared/hooks/usePageTracker';
import { useLanguage } from '../../shared/i18n/LanguageContext';
import { SiteLayout } from '../components/SiteLayout';
import { Mascot } from '../components/Mascot';
import { DiscoveryGuide } from '../components/DiscoveryGuide';
import { FeatureArt } from '../components/FeatureArt';

export function HomePage() {
  const { locale, pathFor } = useLanguage(), en = locale === 'en';
  usePageMeta('Đặng Văn Tiến — Mobile Developer & ChatDVT', { description: en ? 'Đặng Văn Tiến, a React Native and Android/Kotlin Mobile Developer in Ho Chi Minh City. Explore Playground and meet ChatDVT, my AI chat bot on the web and Discord.' : 'Đặng Văn Tiến, Mobile Developer React Native và Android/Kotlin tại TP.HCM. Khám phá Playground và ChatDVT, AI chat bot của mình trên web và Discord.', schema: 'website' });
  usePageTracker('Home');
  return <SiteLayout><section className="hybrid-view hybrid-a selected-home">
    <div className="home-landscape">
      <div className="home-copy"><p className="eyebrow light">ĐẶNG VĂN TIẾN · MOBILE DEVELOPER</p><h1>{en ? <>I’m Tiến.<br /><em>Mobile Developer.</em></> : <>Mình là Tiến.<br /><em>Mobile Developer.</em></>}</h1><p>{en ? 'I work with React Native and Android in Ho Chi Minh City, from app features to native SDKs. Outside work, I play with little features and games, and make ChatDVT, my AI chat bot.' : 'Mình làm React Native và Android ở TP.HCM, từ tính năng app đến SDK native. Ngoài giờ, mình nghịch vài tính năng, game và làm ChatDVT, AI chat bot của mình.'}</p><div className="home-stack"><span>React Native</span><span>Android / Kotlin</span><span>Native SDK</span></div><div className="actions"><Link className="button orange" to={pathFor('/playground')}>{en ? 'Explore Playground' : 'Khám phá Playground'} ↗</Link><Link className="under-link light" to={pathFor('/chat')}>{en ? 'Chat now' : 'Chat ngay'} ↗</Link></div></div>
      <div className="discovery-scene story-scene" aria-label={en ? 'Tiến and paths to explore' : 'Tiến và những lối khám phá'}><div className="scene-orbit" aria-hidden="true" /><div className="scene-hill" aria-hidden="true" /><div className="scene-road" aria-hidden="true" /><span className="scene-location">{en ? 'Go on, try something.' : 'Ở đây, cứ thử nhé.'}</span><Mascot character="tien" className="home-tien" size={290} action="coffee" /><Link className="scene-sign mobile-sign" to={pathFor('/playground?category=mobile')}><span>01 / MOBILE</span>{en ? 'Try it on mobile' : 'Thử trên mobile'} ↗</Link><Link className="scene-sign fun-sign" to={pathFor('/playground?category=fun')}><span>03 / {en ? 'FUN' : 'GIẢI TRÍ'}</span>{en ? 'Play a little' : 'Chơi một chút'} ↗</Link><Link className="scene-sign tools-sign" to={pathFor('/playground?category=tools')}><span>02 / TOOL</span>{en ? 'Try an idea' : 'Thử một ý tưởng'} ↗</Link></div>
      <DiscoveryGuide page="home" className="home-guide" size={82} />
    </div>
    <div className="home-follow page-shell"><div className="section-intro"><p className="eyebrow">{en ? 'MOBILE WORK / SIDE PROJECTS' : 'CÔNG VIỆC MOBILE / SIDE PROJECTS'}</p><h2>{en ? <>React Native.<br />Android & SDKs.</> : <>React Native.<br />Android & SDK.</>}</h2><p>{en ? 'My work revolves around React Native and Android. Outside work, curiosity often becomes a tool, a game, or ChatDVT.' : 'Công việc của mình xoay quanh React Native và Android. Ngoài giờ, những điều tò mò thường biến thành một công cụ, một trò chơi, hoặc ChatDVT.'}</p></div><div className="home-paths"><Link to={pathFor('/playground')} className="home-path"><FeatureArt id="deeplink" label={en ? 'Chibi phone and deep link tools' : 'Minh họa chibi công cụ mobile'} /><div><span className="eyebrow">{en ? 'COME EXPLORE' : 'VÀO KHÁM PHÁ'}</span><h3>Playground.</h3><p>{en ? 'A few features, games and fun little tools. Come try something.' : 'Một vài tính năng, game và tool vui vẻ. Vào nghịch một chút nhé.'}</p><span className="under-link">{en ? 'Explore Playground' : 'Khám phá Playground'} ↗</span></div></Link><Link to={pathFor('/discord')} className="home-path"><div><span className="eyebrow">{en ? 'FROM CURIOSITY' : 'TỪ SỰ TÒ MÒ'}</span><h3>{en ? <>ChatDVT.<br />My AI chat bot.</> : <>ChatDVT.<br />AI chat bot của mình.</>}</h3><p>{en ? 'My AI chat bot, here to chat and introduce this website. You can find ChatDVT on Discord too.' : 'AI chat bot của mình, ở đây để trò chuyện và giới thiệu website này. ChatDVT cũng có mặt trên Discord.'}</p><span className="under-link">{en ? 'Meet ChatDVT' : 'Gặp ChatDVT'} ↗</span></div><Mascot character="chatdvt" size={145} /></Link></div></div>
    <div className="home-writing page-shell"><span className="eyebrow">{en ? 'TIẾN’S NOTES' : 'GHI CHÉP CỦA TIẾN'} · 23/09/2026</span><h2><Link to={pathFor('/blog/chatdvt-phan-1')}>{en ? <>Why did a Mobile Dev<br />start making a bot?</> : <>Vì sao một Mobile Dev<br />lại đi làm bot?</>} <span>↗</span></Link></h2><p>{en ? 'It started with a small disagreement with my coworkers.' : 'Câu chuyện bắt đầu từ một lần dỗi mấy ông đồng nghiệp.'}</p></div>
  </section></SiteLayout>;
}
