import { Link } from 'react-router-dom';
import { usePageMeta } from '../../shared/hooks/usePageMeta';
import { usePageTracker } from '../../shared/hooks/usePageTracker';
import { useLanguage } from '../../shared/i18n/LanguageContext';
import { SiteLayout } from '../components/SiteLayout';
import { Mascot } from '../components/Mascot';
import { FeatureArt } from '../components/FeatureArt';

export function HomePage() {
  const { locale, pathFor } = useLanguage(), en = locale === 'en';
  usePageMeta('Đặng Văn Tiến — Mobile Developer', { description: en ? 'Đặng Văn Tiến is a Mobile Developer in Ho Chi Minh City, working with React Native and Android/Kotlin. Notes, tools, games and side projects.' : 'Đặng Văn Tiến là Mobile Developer ở TP.HCM, chủ yếu làm React Native và Android/Kotlin. Blog, tool, game và các side project của mình.', schema: 'website' });
  usePageTracker('Home');
  return <SiteLayout><section className="hybrid-view hybrid-a selected-home">
    <div className="home-landscape">
      <div className="home-copy"><p className="eyebrow light">ĐẶNG VĂN TIẾN · MOBILE DEVELOPER</p><h1>{en ? <>I’m Tiến.<br /><em>Mobile Developer.</em></> : <>Mình là Tiến.<br /><em>Mobile Developer.</em></>}</h1><p>{en ? 'I’m a Mobile Developer in Ho Chi Minh City, mainly working with React Native and Android/Kotlin. Outside work, I build small tools, games and side projects.' : 'Mình làm Mobile Developer ở TP.HCM, chủ yếu với React Native và Android/Kotlin. Ngoài giờ làm, mình viết vài tool, làm game và nghịch side project.'}</p><div className="home-stack"><span>React Native</span><span>Android / Kotlin</span><span>Native SDK</span></div><div className="actions"><Link className="button orange" to={pathFor('/playground')}>{en ? 'Explore Playground' : 'Xem Playground'} ↗</Link><Link className="under-link light" to={pathFor('/chat')}>{en ? 'Chat now' : 'Chat ngay'} ↗</Link></div></div>
      <div className="discovery-scene story-scene" aria-label={en ? 'Tiến and paths to explore' : 'Tiến và các mục trên website'}><div className="scene-orbit" aria-hidden="true" /><div className="scene-hill" aria-hidden="true" /><div className="scene-road" aria-hidden="true" /><span className="scene-location">{en ? 'Go on, try something.' : 'Tool, game và vài thứ đang làm.'}</span><Mascot character="tien" className="home-tien" size={290} action="coffee" /><Link className="scene-sign mobile-sign" to={pathFor('/playground?category=mobile')}><span>01 / MOBILE</span>{en ? 'Try it on mobile' : 'Tool cho mobile'} ↗</Link><Link className="scene-sign fun-sign" to={pathFor('/playground?category=fun')}><span>03 / {en ? 'FUN' : 'GIẢI TRÍ'}</span>{en ? 'Play a little' : 'Chơi một chút'} ↗</Link><Link className="scene-sign tools-sign" to={pathFor('/playground?category=tools')}><span>02 / TOOL</span>{en ? 'Try an idea' : 'Dùng thử tool'} ↗</Link></div>

    </div>
    <div className="home-follow page-shell"><div className="section-intro"><p className="eyebrow">{en ? 'MOBILE WORK / SIDE PROJECTS' : 'CÔNG VIỆC MOBILE / SIDE PROJECTS'}</p><h2>{en ? <>React Native.<br />Android & SDKs.</> : <>React Native.<br />Android & SDK.</>}</h2><p>{en ? 'I work on mobile apps and SDKs. The tools and games here are things I build outside work.' : 'Công việc chính của mình là làm app và SDK mobile. Những tool và game trên đây là mấy thứ mình làm ngoài giờ.'}</p></div><div className="home-paths"><Link to={pathFor('/playground')} className="home-path"><FeatureArt id="deeplink" label={en ? 'Chibi phone and deep link tools' : 'Minh họa chibi công cụ mobile'} /><div><span className="eyebrow">{en ? 'COME EXPLORE' : 'TOOL & GAME'}</span><h3>Playground.</h3><p>{en ? 'A few features, games and fun little tools. Come try something.' : 'Mấy tool dùng khi làm việc, cùng vài game để chơi lúc rảnh.'}</p><span className="under-link">{en ? 'Explore Playground' : 'Xem Playground'} ↗</span></div></Link><Link to={pathFor('/discord')} className="home-path"><div><span className="eyebrow">SIDE PROJECT</span><h3>{en ? <>ChatDVT.<br />My AI bot.</> : <>ChatDVT.<br />Bot AI của mình.</>}</h3><p>{en ? 'A bot I started building for our 8D group. It chats, analyzes images and video, summarizes messages and runs mini games on Discord. There is a web chat here too.' : 'Con bot mình làm để nghịch với nhóm 8D. Bot có chat AI, phân tích ảnh/video, tóm tắt tin nhắn và mini game trên Discord. Có cả bản chat trên web này.'}</p><span className="under-link">{en ? 'See ChatDVT' : 'Xem ChatDVT'} ↗</span></div><Mascot character="chatdvt" size={145} /></Link></div></div>
    <div className="home-writing page-shell"><span className="eyebrow">{en ? 'TIẾN’S NOTES' : 'GHI CHÉP CỦA TIẾN'} · 23/09/2026</span><h2><Link to={pathFor('/blog/chatdvt-phan-1')}>{en ? <>Why did a Mobile Dev<br />start making a bot?</> : <>Vì sao một Mobile Dev<br />lại đi làm bot?</>} <span>↗</span></Link></h2><p>{en ? 'It started with a small disagreement with my coworkers.' : 'Câu chuyện bắt đầu từ một lần dỗi mấy ông đồng nghiệp.'}</p></div>
  </section></SiteLayout>;
}
