import { Link } from 'react-router-dom';
import { usePageMeta } from '../../shared/hooks/usePageMeta';
import { usePageTracker } from '../../shared/hooks/usePageTracker';
import { useLanguage } from '../../shared/i18n/LanguageContext';
import { SiteLayout } from '../components/SiteLayout';
import { Mascot } from '../components/Mascot';
import { DiscoveryGuide } from '../components/DiscoveryGuide';
import { FeatureArt } from '../components/FeatureArt';
import { profile, contributions, skillFamilies } from '../content/profileData';

export function MePage() {
  const { locale, pathFor } = useLanguage(), en = locale === 'en', language = en ? 1 : 0;
  usePageMeta(en ? 'About Đặng Văn Tiến — React Native & Android Engineer' : 'Về Đặng Văn Tiến — Kỹ sư React Native & Android', { description: en ? 'Meet Đặng Văn Tiến: React Native, Android and native SDK work at South Telecom, professional experience, side projects and contact information.' : 'Tìm hiểu Đặng Văn Tiến: kinh nghiệm React Native, Android và SDK native tại South Telecom, các side project và thông tin liên hệ.', schema: 'profile' });
  usePageTracker('Me');
  return <SiteLayout><section className="hybrid-view hybrid-b selected-me">
    <div className="me-stage band profile-stage"><div className="portrait-wrap"><img src="/images/tien-dang-profile.jpg" alt={en ? 'Portrait of Đặng Văn Tiến' : 'Chân dung Đặng Văn Tiến'} width={320} height={320} /><span>{en ? 'HO CHI MINH CITY' : 'TP. HỒ CHÍ MINH'}</span></div><div><p className="eyebrow">{en ? 'NICE TO MEET YOU' : 'RẤT VUI ĐƯỢC GẶP BẠN'}</p><h1>Đặng Văn<br />Tiến<span>.</span></h1><p className="lede">{profile.role}.<br />{en ? 'React Native, Android and the bridges between them.' : 'React Native, Android và những cầu nối giữa chúng.'}</p><div className="contacts"><a href={'mailto:' + profile.email}>Email ↗</a><a href={profile.github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></div>
    <div className="work-section" id="experience"><div className="work-heading"><p className="eyebrow">{en ? 'WORK' : 'CÔNG VIỆC'}</p><h2>{profile.company}</h2><p>{profile.role}<br />{profile.period} — {en ? 'present' : 'hiện tại'}</p></div><ol className="contribution-list">{contributions.map(item => <li key={item.title[0]}><h3>{item.title[language]}</h3><p>{item.description[language]}</p></li>)}</ol></div>
    <div className="skills-section band deep-stage"><div><p className="eyebrow">{en ? 'TOOLS FOR WORK' : 'CÔNG CỤ CHO CÔNG VIỆC'}</p><h2>{en ? <>From interfaces<br />to Native.</> : <>Từ giao diện<br />đến Native.</>}</h2></div><dl>{skillFamilies.map(group => <div key={group.title}><dt>{group.title}</dt><dd>{group.items}</dd></div>)}<div><dt>{en ? 'Education' : 'Học vấn'}</dt><dd>{en ? 'Software Engineering' : 'Kỹ thuật phần mềm'} · PTIT · 2017–2022</dd></div></dl></div>
    <div className="sidework"><p className="eyebrow">{en ? 'BY TIẾN · OUTSIDE WORK' : 'DO TIẾN LÀM · NGOÀI GIỜ'}</p><h2>Side projects.<br />{en ? 'Somewhere to learn, too.' : 'Cũng là chỗ để học.'}</h2><div className="sidework-links"><Link to={pathFor('/playground?category=mobile')}><FeatureArt id="deeplink" label={en ? 'Chibi mobile toolkit' : 'Minh họa chibi bộ công cụ mobile'} /><h3>Mobile Developer Toolkit</h3><p>{en ? 'Tools for testing, debugging and learning.' : 'Những thứ dùng để test, debug và đọc tài liệu.'}</p><span className="underlined">{en ? 'See Mobile' : 'Xem Mobile'} ↗</span></Link><Link to={pathFor('/playground?category=tools')}><FeatureArt id="mermaid" label={en ? 'Chibi diagram tools' : 'Minh họa chibi công cụ tạo sơ đồ'} /><h3>{en ? 'Tools & experiments' : 'Tool & thử nghiệm'}</h3><p>{en ? 'Mermaid, Note Daily, English Hub and small ideas.' : 'Mermaid, Note Daily, English Hub và những ý tưởng nhỏ.'}</p><span className="underlined">{en ? 'See Tools' : 'Xem Tool'} ↗</span></Link></div></div>
    <div className="friend-section band soft-stage"><div className="story-scene"><Mascot character="tien" size={235} /><Mascot character="chatdvt" size={160} /></div><div><p className="eyebrow">{en ? 'A SIDE PROJECT. A FRIEND.' : 'MỘT SIDE PROJECT. MỘT NGƯỜI BẠN.'}</p><h2>{en ? <>Meet my friend,<br />ChatDVT.</> : <>Một người bạn<br />tên ChatDVT.</>}</h2><p>{en ? 'ChatDVT is my AI chat bot and a friend who introduces this website. You can chat here or meet ChatDVT on Discord.' : 'ChatDVT là AI chat bot của mình và là người bạn giới thiệu website này. Bạn có thể chat ở đây hoặc gặp ChatDVT trên Discord.'}</p><Link className="button ink" to={pathFor('/discord')}>{en ? 'Meet ChatDVT' : 'Gặp ChatDVT'} ↗</Link><Link className="text-link" to={pathFor('/chat')}>{en ? 'Chat here' : 'Trò chuyện ở đây'} →</Link></div></div>
    <DiscoveryGuide page="me" className="slim-guide" size={100} />
  </section></SiteLayout>;
}
