import { Link } from 'react-router-dom';
import { usePageMeta } from '../../shared/hooks/usePageMeta';
import { usePageTracker } from '../../shared/hooks/usePageTracker';
import { useLanguage } from '../../shared/i18n/LanguageContext';
import { SiteLayout } from '../components/SiteLayout';
import { Mascot } from '../components/Mascot';
import { profile, contributions, skillFamilies } from '../content/profileData';

export function MePage() {
  const { locale, pathFor } = useLanguage(), en = locale === 'en', language = en ? 1 : 0;
  usePageMeta(en ? 'About Đặng Văn Tiến — React Native & Android Engineer' : 'Về Đặng Văn Tiến — Kỹ sư React Native & Android', { description: en ? 'Đặng Văn Tiến is a Mobile Developer at South Telecom in Ho Chi Minh City, a PTIT Ho Chi Minh City alumnus (2017–2022), working on React Native, Android/Kotlin and ChatDVT.' : 'Đặng Văn Tiến là Mobile Developer tại South Telecom ở TP.HCM, làm React Native và Android/Kotlin, cựu sinh viên PTIT HCM (2017–2022) và là người làm bot ChatDVT.', schema: 'profile' });
  usePageTracker('Me');
  return <SiteLayout><section className="hybrid-view hybrid-b selected-me">
    <div className="me-stage band profile-stage"><div className="portrait-wrap"><img src="/images/tien-dang-profile.jpg" alt={en ? 'Portrait of Đặng Văn Tiến' : 'Chân dung Đặng Văn Tiến'} width={320} height={320} /><span>{en ? 'HO CHI MINH CITY' : 'TP. HỒ CHÍ MINH'}</span></div><div><p className="eyebrow">{en ? 'NICE TO MEET YOU' : 'VỀ MÌNH'}</p><h1>Đặng Văn<br />Tiến<span>.</span></h1><p className="lede">{profile.role}.<br />{en ? 'I’m a mobile developer. I mainly work with React Native and Android, and occasionally build things I find interesting.' : 'Mình là một lập trình viên ứng dụng di động. Chủ yếu làm việc với React Native và Android, thỉnh thoảng tự làm thêm những thứ mình thấy thú vị.'}</p><div className="contacts"><a href={'mailto:' + profile.email}>Email ↗</a><a href={profile.github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></div>
    <div className="work-section" id="experience"><div className="work-heading"><p className="eyebrow">{en ? 'WORK' : 'CÔNG VIỆC'}</p><h2>{profile.company}</h2><p>{profile.role}<br />{profile.period} — {en ? 'present' : 'hiện tại'}</p></div><ol className="contribution-list">{contributions.map(item => <li key={item.title[0]}><h3>{item.title[language]}</h3><p>{item.description[language]}</p></li>)}</ol></div>
    <div className="skills-section band deep-stage"><div><p className="eyebrow">{en ? 'TECHNOLOGY' : 'CÔNG NGHỆ'}</p><h2>Tech stack.</h2></div><dl>{skillFamilies.map(group => <div key={group.title}><dt>{group.title}</dt><dd>{group.items}</dd></div>)}</dl></div>
    <div className="work-section" id="education"><div className="work-heading"><p className="eyebrow">{en ? 'EDUCATION' : 'HỌC VẤN'}</p><h2>PTITHCM</h2><p>2017–2022</p></div><ol className="contribution-list"><li><h3>{en ? 'Software Engineering' : 'Kỹ thuật phần mềm'}</h3><p>{en ? 'Alumnus of the Posts and Telecommunications Institute of Technology, Ho Chi Minh City campus.' : 'Cựu sinh viên Học viện Công nghệ Bưu chính Viễn thông, cơ sở TP.HCM.'}</p></li></ol></div>
    <div className="friend-section band soft-stage"><div className="story-scene"><Mascot character="tien" size={235} /><Mascot character="chatdvt" size={160} /></div><div><p className="eyebrow">SIDE PROJECT</p><h2>ChatDVT.</h2><p>{en ? 'ChatDVT started as a bot I built for our 8D group. Its backend uses TypeScript and Discord.js, with Google Gemini for AI. It supports chat, media analysis, summaries and Discord mini games, plus web chat.' : 'ChatDVT ban đầu chỉ là một con bot mình làm để nghịch với nhóm 8D. Backend viết bằng TypeScript và Discord.js, phần AI dùng Google Gemini. Giờ bot có thể chat, phân tích ảnh/video, tóm tắt tin nhắn và chơi mini game trên Discord. Bạn cũng có thể chat với bot ngay trên web.'}</p><Link className="button ink" to={pathFor('/discord')}>{en ? 'Meet ChatDVT' : 'Xem Discord bot'} ↗</Link><Link className="text-link" to={pathFor('/chat')}>{en ? 'Chat here' : 'Trò chuyện ở đây'} →</Link></div></div>

  </section></SiteLayout>;
}
