import { Link } from 'react-router-dom';
import { WALLPAPER_APP } from '../../../../src/shared/desktopApps';
import { usePageMeta } from '../../shared/hooks/usePageMeta';
import { usePageTracker } from '../../shared/hooks/usePageTracker';
import { useLanguage } from '../../shared/i18n/LanguageContext';
import { SiteLayout } from '../components/SiteLayout';

export function WallpaperAppPage() {
  const { locale, pathFor } = useLanguage(), en = locale === 'en';
  usePageMeta(en ? 'TD-WallpaperEngine — Image & video wallpapers for Windows' : 'TD-WallpaperEngine — Hình nền ảnh & video cho Windows', {
    description: WALLPAPER_APP.description[locale], image: WALLPAPER_APP.image,
    imageAlt: en ? 'TD-WallpaperEngine wallpaper library' : 'Thư viện hình nền TD-WallpaperEngine',
    schema: 'software', schemaName: WALLPAPER_APP.name,
  });
  usePageTracker('TD-WallpaperEngine');
  const steps = en ? [
    'Download the installer, or extract the portable ZIP and run TienDang.Wallpaper.exe.',
    'Try a bundled wallpaper or use Add wallpaper to import your own files or a URL.',
    'Select a wallpaper to preview it, then choose Set as wallpaper.',
    'Enable automatic rotation if you want to cycle through your collection.',
  ] : [
    'Tải bản cài đặt, hoặc giải nén bản portable rồi chạy TienDang.Wallpaper.exe.',
    'Thử hình nền có sẵn, hoặc dùng Add wallpaper để thêm file hay URL của bạn.',
    'Chọn hình nền để xem trước, rồi bấm Set as wallpaper.',
    'Bật tự đổi hình nền nếu muốn dùng luân phiên cả bộ sưu tập.',
  ];
  return <SiteLayout><article className="site-container apps-page wallpaper-page">
    <Link className="apps-back" to={pathFor('/apps')}>← {en ? 'Apps & software' : 'Ứng dụng & phần mềm'}</Link>
    <header className="wallpaper-opening"><div><p className="site-kicker">WINDOWS APP · {en ? 'BY ĐẶNG VĂN TIẾN' : 'ĐẶNG VĂN TIẾN'}</p><h1>{WALLPAPER_APP.name}</h1><p className="wallpaper-lede">{en ? 'Images and videos, right on your desktop.' : 'Ảnh và video làm hình nền desktop.'}</p><p>{WALLPAPER_APP.description[locale]}</p><div className="apps-actions"><a className="apps-button" href="#download">{en ? 'Download for Windows' : 'Tải cho Windows'} ↓</a><a className="apps-text-link" href={WALLPAPER_APP.sourceUrl} target="_blank" rel="noreferrer">Source code ↗</a><a className="apps-text-link" href={WALLPAPER_APP.demoUrl} target="_blank" rel="noreferrer">{en ? 'Watch demo' : 'Xem demo'} ↗</a></div></div><aside className="wallpaper-facts" aria-label={en ? 'App information' : 'Thông tin ứng dụng'}><dl><div><dt>{en ? 'Platform' : 'Nền tảng'}</dt><dd>Windows 10 / 11 · 64-bit</dd></div><div><dt>{en ? 'Release' : 'Bản phát hành'}</dt><dd>{WALLPAPER_APP.version}</dd></div><div><dt>{en ? 'Language' : 'Ngôn ngữ'}</dt><dd>{en ? 'Vietnamese / English' : 'Tiếng Việt / English'}</dd></div><div><dt>Tech stack</dt><dd>{WALLPAPER_APP.stack.join(' · ')}</dd></div></dl></aside></header>
    <figure className="wallpaper-preview"><a href={WALLPAPER_APP.image} target="_blank" rel="noreferrer" aria-label={en ? 'Open full library screenshot' : 'Mở ảnh thư viện đầy đủ'}><img src={WALLPAPER_APP.image} alt={en ? 'TD-WallpaperEngine library, wallpaper preview and automatic rotation controls' : 'Thư viện, phần xem trước hình nền và thanh tự đổi hình của TD-WallpaperEngine'} width={1380} height={880} /></a><figcaption>{en ? 'Actual app screenshot from the repository. Select a wallpaper, preview it and apply it from the same window.' : 'Ảnh giao diện thật từ repo. Chọn hình nền, xem trước và áp dụng ngay trong cùng cửa sổ.'}</figcaption></figure>
    <section className="wallpaper-section" aria-labelledby="wallpaper-features"><p className="site-kicker">{en ? 'WHAT IT DOES' : 'APP LÀM ĐƯỢC GÌ'}</p><h2 id="wallpaper-features">{en ? 'A wallpaper library, with a few extras.' : 'Hình nền và vài thứ đi kèm.'}</h2><div className="wallpaper-features">{WALLPAPER_APP.features[locale].map((feature, index) => <div key={feature.title}><span aria-hidden="true">0{index + 1}</span><h3>{feature.title}</h3><p>{feature.text}</p></div>)}</div></section>
    <section className="wallpaper-performance" aria-labelledby="wallpaper-performance"><div><p className="site-kicker">{en ? 'PLAYBACK & PERFORMANCE' : 'PLAYBACK & TÀI NGUYÊN'}</p><h2 id="wallpaper-performance">{en ? 'Pause when you need the resources.' : 'Cần tài nguyên thì tạm dừng.'}</h2><p>{en ? 'Set the app to pause video wallpapers when another app is fullscreen or maximized, when running on battery, or through per-app rules.' : 'Có thể cho app tạm dừng video khi cửa sổ khác chạy toàn màn hình, phóng to, khi dùng pin hoặc theo rule riêng cho từng app.'}</p><p>{en ? 'The optional memory-saving mode releases the player while paused. You can also adjust FPS, volume and how the wallpaper fits your screen.' : 'Chế độ tiết kiệm bộ nhớ sẽ giải phóng player khi tạm dừng. Bạn cũng có thể chỉnh FPS, âm lượng và cách hình nền vừa với màn hình.'}</p></div><figure><a href={WALLPAPER_APP.settingsImage} target="_blank" rel="noreferrer" aria-label={en ? 'Open full settings screenshot' : 'Mở ảnh cài đặt đầy đủ'}><img src={WALLPAPER_APP.settingsImage} alt={en ? 'Language, display fit, FPS and volume settings' : 'Cài đặt ngôn ngữ, cách căn hình, FPS và âm lượng'} width={744} height={760} loading="lazy" /></a><figcaption>{en ? 'Playback settings in the app.' : 'Các tùy chọn playback trong app.'}</figcaption></figure></section>
    <section className="wallpaper-section wallpaper-start" aria-labelledby="wallpaper-start"><div><p className="site-kicker">{en ? 'QUICK START' : 'BẮT ĐẦU DÙNG'}</p><h2 id="wallpaper-start">{en ? 'Download, pick a wallpaper, apply.' : 'Tải app, chọn hình, áp dụng.'}</h2></div><div><ol>{steps.map(step => <li key={step}>{step}</li>)}</ol><p>{en ? 'Closing the window keeps the app running in the system tray. Choose Exit in the tray menu to stop it completely.' : 'Đóng cửa sổ thì app vẫn chạy ở system tray. Muốn tắt hẳn, chọn Exit trong menu của biểu tượng dưới taskbar.'}</p></div></section>
    <section id="download" className="wallpaper-download" aria-labelledby="wallpaper-download"><p className="site-kicker">WINDOWS 10 / 11 · 64-BIT</p><h2 id="wallpaper-download">{en ? 'Get TD-WallpaperEngine.' : 'Tải TD-WallpaperEngine.'}</h2><p>{en ? 'The GitHub release page has an installer and a portable ZIP. The latest release is always available through the link below.' : 'Trang Releases trên GitHub có bản cài đặt và bản ZIP portable. Link dưới luôn dẫn tới bản phát hành mới nhất.'}</p><div className="apps-actions"><a className="apps-button" href={WALLPAPER_APP.releasesUrl} target="_blank" rel="noreferrer">{en ? 'Download on GitHub' : 'Tải trên GitHub'} ↗</a><a className="apps-text-link" href={`${WALLPAPER_APP.sourceUrl}/issues`} target="_blank" rel="noreferrer">{en ? 'Report an issue' : 'Báo lỗi'} ↗</a></div><ul><li>{en ? 'Requires Windows 10/11 x64 and a GPU with Direct3D 11 support.' : 'Cần Windows 10/11 x64 và GPU hỗ trợ Direct3D 11.'}</li><li>{en ? 'The required runtime and media tools are included; no separate .NET or player installation is needed.' : 'Bản tải đã kèm runtime và media tool; không cần cài riêng .NET hay player.'}</li><li>{en ? 'Exit the previous version before installing an update. Your library and settings are preserved.' : 'Thoát bản cũ trước khi cập nhật. Thư viện và cài đặt được giữ lại.'}</li></ul><p className="wallpaper-independence">{en ? 'This is my own app. It runs independently of Steam and Wallpaper Engine.' : 'Đây là app riêng mình làm, chạy độc lập với Steam và Wallpaper Engine.'} <Link to={pathFor('/me')}>{en ? 'About Tiến' : 'Về Tiến'} ↗</Link></p></section>
  </article></SiteLayout>;
}
