import { DeeplinkPreset } from '../types/deeplink';

export const DEFAULT_PRESETS: DeeplinkPreset[] = [
  {
    id: 'generic_custom',
    name: 'Custom App Scheme',
    category: 'standard',
    url: 'myapp://product/detail?id=1024&ref=portal_test',
    description: 'URL scheme mẫu với path và query params',
    packageName: 'com.example.myapp',
  },
  {
    id: 'generic_universal',
    name: 'Universal / App Link',
    category: 'standard',
    url: 'https://example.com/item/detail?sku=VN-8899&promo=FALL2026',
    description: 'HTTPS Universal Link (iOS) hoặc Android App Link',
    packageName: 'com.example.myapp',
  },
  {
    id: 'generic_intent',
    name: 'Android Intent Scheme',
    category: 'standard',
    url: 'intent://product/detail?id=1024#Intent;scheme=myapp;package=com.example.myapp;S.browser_fallback_url=https%3A%2F%2Fplay.google.com;end',
    description: 'Chuẩn Chrome Android Intent với fallback url',
    packageName: 'com.example.myapp',
  },
  {
    id: 'momo_payment',
    name: 'MoMo Payment',
    category: 'vietnam',
    url: 'momo://?action=pay&amount=50000&extra=deeplink_test',
    description: 'Kích hoạt thanh toán MoMo',
    packageName: 'com.mservice.momotransfer',
  },
  {
    id: 'zalo_chat',
    name: 'Zalo Chat Direct',
    category: 'vietnam',
    url: 'zalo://chat?phone=0901234567',
    description: 'Mở cửa sổ chat với số điện thoại trong Zalo',
    packageName: 'com.zing.zalo',
  },
  {
    id: 'zalo_qr',
    name: 'Zalo QR Scan',
    category: 'vietnam',
    url: 'zalo://qr/p/',
    description: 'Mở nhanh máy quét QR của Zalo',
    packageName: 'com.zing.zalo',
  },
  {
    id: 'shopee_product',
    name: 'Shopee Product',
    category: 'vietnam',
    url: 'shopee://product/1234567/89101112',
    description: 'Mở trang chi tiết sản phẩm trên Shopee',
    packageName: 'com.shopee.vn',
  },
  {
    id: 'telegram_resolve',
    name: 'Telegram User/Channel',
    category: 'social',
    url: 'tg://resolve?domain=telegram',
    description: 'Mở kênh hoặc người dùng trong Telegram',
    packageName: 'org.telegram.messenger',
  },
  {
    id: 'youtube_watch',
    name: 'YouTube Video',
    category: 'social',
    url: 'vnd.youtube://watch?v=dQw4w9WgXcQ',
    description: 'Mở video trực tiếp trong YouTube app',
    packageName: 'com.google.android.youtube',
  },
  {
    id: 'facebook_profile',
    name: 'Facebook Profile',
    category: 'social',
    url: 'fb://profile/4',
    description: 'Mở trang cá nhân trong Facebook app',
    packageName: 'com.facebook.katana',
  },
  {
    id: 'system_tel',
    name: 'Call Phone (tel:)',
    category: 'system',
    url: 'tel:+84987654321',
    description: 'Mở trình quay số điện thoại',
  },
  {
    id: 'system_sms',
    name: 'Send SMS (sms:)',
    category: 'system',
    url: 'sms:+84987654321?body=Xin%20chao%20tu%20Deeplink%20Tester',
    description: 'Mở ứng dụng tin nhắn với nội dung điền sẵn',
  },
  {
    id: 'system_mail',
    name: 'Send Email (mailto:)',
    category: 'system',
    url: 'mailto:contact@example.com?subject=Deeplink%20Audit&body=Hello%20Team',
    description: 'Mở ứng dụng Mail mặc định',
  },
  {
    id: 'system_maps',
    name: 'Open Maps (geo:)',
    category: 'system',
    url: 'geo:10.7769,106.7009?q=Bitexco+Financial+Tower',
    description: 'Mở vị trí địa lý trên bản đồ',
  }
];
